services:
  server:
    build: .
    container_name: server
    env_file: ./.env
    ports:
      - 3000
    networks:
      - app-network

  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - '80:80'
    depends_on:
      - server
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
